### ISSUE TITLE
Issues with Installing MetaMapR

### ISSUE THREAD

**Issue by Transmystical** [dgrapov/MetaMapR#4]
Dear MetaMapR Wizards: 

I am currently trying to install MetaMapR. I have tried the following: 

1) **In R**  - ran the command, which only populated the following error
`library(shiny)`
`shiny::runGitHub('MetaMapR','dgrapov')`
Downloading https://github.com/dgrapov/MetaMapR/archive/master.tar.gz

> Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

2) **Downloaded the MetaMapR-master.tar.gz**, unzipped it and read the README.html which states to run the following command, to which I got the same error: 
`library(shiny)`
`shiny::runApp('~/../Desktop/MetaMapR-master')`

> Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

Due to this, I created a sym link to bring in the R.app into the MetaMapR-master directory: 
`$ cd /Desktop/MetaMapR-master `
`$ ln -s /Applications/R.app .`

$ ls 
LICENSE **R.app** README_files version.html version_info.txt
Manual README.Rmd	SVGnetwork.html version.md	 www
MetaMapR.Rproj README.html screenshots.md	version_files
NEWS.md README.md	version.Rmd version_info

Next I ran the same previous command and got the same error: 
`shiny::runApp('~/../Desktop/MetaMapR-master')`

> Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

Any advice on how to download MetaMapR? 

Many Thanks!

**Comment by dgrapov** [comment]
Hi,

You can find the underlying functionality for metamapr as an R package here https://github.com/dgrapov/metabomapr

The UI components were migrated to a hosted server: http://createdatasol.com/ .

**Comment by Transmystical** [comment]
Thank you for your reply. However, I am not exactly sure how to download the **MetaMapR** package based on this answer. 

I have ran the following code, as suggested on the link provided above, only to get an error: 
`devtools::install_github("dgrapov/metabomapr")`

> DownloadingGitHub repo dgrapov/metabomapr@master
from URL https://api.github.com/repos/dgrapov/metabomapr/zipball/master
Installing metabomapr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/z4/jfbc76zs7_l8q_4xb8rgtmf00000gn/T/Rtmp1b9BpR/devtools2c2520f2d4d5/dgrapov-metabomapr-e400f0d'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 
ERROR: dependency ‘ChemmineR’ is not available for package ‘metabomapr’
*removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/metabomapr’
Installation failed: Command failed (1)

From here, I installed the ChemmineR package from Bioconductor: 
`source("https://bioconductor.org/biocLite.R")`
`biocLite("ChemmineR")`
`library(ChemmineR)`

After successful download, I re-ran the 
`devtools::install_github("dgrapov/metabomapr")`
`library(metabomapr)`

Next, I went to the web-site that was suggested: http://createdatasol.com/
which is asking for $10 for a subscription. I did not subscribe. 

Finally, I ran the code to install MetaMapR once again and got the same error that I got from the very beginning: 
`shiny::runGitHub('MetaMapR','dgrapov')`

> Downloading https://github.com/dgrapov/MetaMapR/archive/master.tar.gz
Error in shinyAppDir(x) : App dir must contain either app.R or server.R.

There must be a much more user-friendly and clear way to download this package w/out so many errors and re-directions to another web-site that is asking for money, and installations of other packages with directions in 2 separate links. This is incredibly confusing!!

**Comment by dgrapov** [comment]
Hi,

Sorry for the confusion, but based on your output you successfully installed `metabomapr` which contains core functionality of MetaMapR as documented on the [README](https://github.com/dgrapov/metabomapr/blob/master/README.md). As previously stated `metabomapr` does not contain any UI i.e. shiny components.

**Comment by lxxxx1234** [comment]
Hi,
Transmystical,today,I met the same problem as you, and after a half day, l find how to fix it .
there are something wrong in the profile, specifically，it lost a few programs. 
Here is the fixed profile，and if your problem has not been solved, you can download it ,and installed it by using the second way,and you will do it,good luck!
[MetaMapR-master.zip](https://github.com/dgrapov/MetaMapR/files/1795769/MetaMapR-master.zip)
Also thanks the owner for developing such a good package.

**Comment by Transmystical** [comment]
lxxxx1234: 

I just wanted to say thank you for your comment and input. Yes - I was able to get it up and running with the .zip file you provided. Works great now.
